//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.ServiceUserProfile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class PlayerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsToNextLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceUserProfile.PlayerStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int currentPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathPhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsToNextLevel {
            get {
                return this.PointsToNextLevelField;
            }
            set {
                if ((this.PointsToNextLevelField.Equals(value) != true)) {
                    this.PointsToNextLevelField = value;
                    this.RaisePropertyChanged("PointsToNextLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName {
            get {
                return this.RankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RankNameField, value) != true)) {
                    this.RankNameField = value;
                    this.RaisePropertyChanged("RankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceUserProfile.PlayerStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentPoints {
            get {
                return this.currentPointsField;
            }
            set {
                if ((this.currentPointsField.Equals(value) != true)) {
                    this.currentPointsField = value;
                    this.RaisePropertyChanged("currentPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLevel {
            get {
                return this.idLevelField;
            }
            set {
                if ((this.idLevelField.Equals(value) != true)) {
                    this.idLevelField = value;
                    this.RaisePropertyChanged("idLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto {
            get {
                return this.pathPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.pathPhotoField, value) != true)) {
                    this.pathPhotoField = value;
                    this.RaisePropertyChanged("pathPhoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatus", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.Enums")]
    public enum PlayerStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InLobby = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceUserProfile.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceUserProfile.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class SocialDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSocialTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocial {
            get {
                return this.IdSocialField;
            }
            set {
                if ((this.IdSocialField.Equals(value) != true)) {
                    this.IdSocialField = value;
                    this.RaisePropertyChanged("IdSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocialType {
            get {
                return this.IdSocialTypeField;
            }
            set {
                if ((this.IdSocialTypeField.Equals(value) != true)) {
                    this.IdSocialTypeField = value;
                    this.RaisePropertyChanged("IdSocialType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLink {
            get {
                return this.UserLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLinkField, value) != true)) {
                    this.UserLinkField = value;
                    this.RaisePropertyChanged("UserLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameHistoryDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class GameHistoryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpponentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsEarnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameTime {
            get {
                return this.GameTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameTimeField, value) != true)) {
                    this.GameTimeField = value;
                    this.RaisePropertyChanged("GameTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpponentName {
            get {
                return this.OpponentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OpponentNameField, value) != true)) {
                    this.OpponentNameField = value;
                    this.RaisePropertyChanged("OpponentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsEarned {
            get {
                return this.PointsEarnedField;
            }
            set {
                if ((this.PointsEarnedField.Equals(value) != true)) {
                    this.PointsEarnedField = value;
                    this.RaisePropertyChanged("PointsEarned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultStatus {
            get {
                return this.ResultStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultStatusField, value) != true)) {
                    this.ResultStatusField = value;
                    this.RaisePropertyChanged("ResultStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUserProfile.IUserProfile")]
    public interface IUserProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerById", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerByIdServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        ConquiánCliente.ServiceUserProfile.PlayerDto GetPlayerById(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerById", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerByIdResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.PlayerDto> GetPlayerByIdAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayer", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdatePlayerServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void UpdatePlayer(ConquiánCliente.ServiceUserProfile.PlayerDto playerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayer", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerResponse")]
        System.Threading.Tasks.Task UpdatePlayerAsync(ConquiánCliente.ServiceUserProfile.PlayerDto playerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerSocialsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerSocialsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        ConquiánCliente.ServiceUserProfile.SocialDto[] GetPlayerSocials(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerSocialsResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.SocialDto[]> GetPlayerSocialsAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerSocialsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdatePlayerSocialsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void UpdatePlayerSocials(int idPlayer, ConquiánCliente.ServiceUserProfile.SocialDto[] socials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerSocialsResponse")]
        System.Threading.Tasks.Task UpdatePlayerSocialsAsync(int idPlayer, ConquiánCliente.ServiceUserProfile.SocialDto[] socials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdateProfilePicture", ReplyAction="http://tempuri.org/IUserProfile/UpdateProfilePictureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdateProfilePictureServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void UpdateProfilePicture(int idPlayer, string newPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdateProfilePicture", ReplyAction="http://tempuri.org/IUserProfile/UpdateProfilePictureResponse")]
        System.Threading.Tasks.Task UpdateProfilePictureAsync(int idPlayer, string newPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerGameHistory", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerGameHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerGameHistoryServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        ConquiánCliente.ServiceUserProfile.GameHistoryDto[] GetPlayerGameHistory(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerGameHistory", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerGameHistoryResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.GameHistoryDto[]> GetPlayerGameHistoryAsync(int idPlayer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileChannel : ConquiánCliente.ServiceUserProfile.IUserProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileClient : System.ServiceModel.ClientBase<ConquiánCliente.ServiceUserProfile.IUserProfile>, ConquiánCliente.ServiceUserProfile.IUserProfile {
        
        public UserProfileClient() {
        }
        
        public UserProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConquiánCliente.ServiceUserProfile.PlayerDto GetPlayerById(int idPlayer) {
            return base.Channel.GetPlayerById(idPlayer);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.PlayerDto> GetPlayerByIdAsync(int idPlayer) {
            return base.Channel.GetPlayerByIdAsync(idPlayer);
        }
        
        public void UpdatePlayer(ConquiánCliente.ServiceUserProfile.PlayerDto playerDto) {
            base.Channel.UpdatePlayer(playerDto);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerAsync(ConquiánCliente.ServiceUserProfile.PlayerDto playerDto) {
            return base.Channel.UpdatePlayerAsync(playerDto);
        }
        
        public ConquiánCliente.ServiceUserProfile.SocialDto[] GetPlayerSocials(int idPlayer) {
            return base.Channel.GetPlayerSocials(idPlayer);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.SocialDto[]> GetPlayerSocialsAsync(int idPlayer) {
            return base.Channel.GetPlayerSocialsAsync(idPlayer);
        }
        
        public void UpdatePlayerSocials(int idPlayer, ConquiánCliente.ServiceUserProfile.SocialDto[] socials) {
            base.Channel.UpdatePlayerSocials(idPlayer, socials);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerSocialsAsync(int idPlayer, ConquiánCliente.ServiceUserProfile.SocialDto[] socials) {
            return base.Channel.UpdatePlayerSocialsAsync(idPlayer, socials);
        }
        
        public void UpdateProfilePicture(int idPlayer, string newPath) {
            base.Channel.UpdateProfilePicture(idPlayer, newPath);
        }
        
        public System.Threading.Tasks.Task UpdateProfilePictureAsync(int idPlayer, string newPath) {
            return base.Channel.UpdateProfilePictureAsync(idPlayer, newPath);
        }
        
        public ConquiánCliente.ServiceUserProfile.GameHistoryDto[] GetPlayerGameHistory(int idPlayer) {
            return base.Channel.GetPlayerGameHistory(idPlayer);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceUserProfile.GameHistoryDto[]> GetPlayerGameHistoryAsync(int idPlayer) {
            return base.Channel.GetPlayerGameHistoryAsync(idPlayer);
        }
    }
}
