//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.ServiceGuestInvitation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGuestInvitation.IGuestInvitation")]
    public interface IGuestInvitation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestInvitation/SendGuestInvite", ReplyAction="http://tempuri.org/IGuestInvitation/SendGuestInviteResponse")]
        bool SendGuestInvite(string roomCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestInvitation/SendGuestInvite", ReplyAction="http://tempuri.org/IGuestInvitation/SendGuestInviteResponse")]
        System.Threading.Tasks.Task<bool> SendGuestInviteAsync(string roomCode, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestInvitationChannel : ConquiánCliente.ServiceGuestInvitation.IGuestInvitation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestInvitationClient : System.ServiceModel.ClientBase<ConquiánCliente.ServiceGuestInvitation.IGuestInvitation>, ConquiánCliente.ServiceGuestInvitation.IGuestInvitation {
        
        public GuestInvitationClient() {
        }
        
        public GuestInvitationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestInvitationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestInvitationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestInvitationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendGuestInvite(string roomCode, string email) {
            return base.Channel.SendGuestInvite(roomCode, email);
        }
        
        public System.Threading.Tasks.Task<bool> SendGuestInviteAsync(string roomCode, string email) {
            return base.Channel.SendGuestInviteAsync(roomCode, email);
        }
    }
}
