//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.ServiceLobby {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class LobbyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceLobby.MessageDto[] ChatMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceLobby.PlayerDto[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idGamemodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idHostPlayerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceLobby.MessageDto[] ChatMessages {
            get {
                return this.ChatMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatMessagesField, value) != true)) {
                    this.ChatMessagesField = value;
                    this.RaisePropertyChanged("ChatMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceLobby.PlayerDto[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode {
            get {
                return this.RoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCodeField, value) != true)) {
                    this.RoomCodeField = value;
                    this.RaisePropertyChanged("RoomCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusLobby {
            get {
                return this.StatusLobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusLobbyField, value) != true)) {
                    this.StatusLobbyField = value;
                    this.RaisePropertyChanged("StatusLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idGamemode {
            get {
                return this.idGamemodeField;
            }
            set {
                if ((this.idGamemodeField.Equals(value) != true)) {
                    this.idGamemodeField = value;
                    this.RaisePropertyChanged("idGamemode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHostPlayer {
            get {
                return this.idHostPlayerField;
            }
            set {
                if ((this.idHostPlayerField.Equals(value) != true)) {
                    this.idHostPlayerField = value;
                    this.RaisePropertyChanged("idHostPlayer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class MessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class PlayerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int currentPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathPhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentPoints {
            get {
                return this.currentPointsField;
            }
            set {
                if ((this.currentPointsField.Equals(value) != true)) {
                    this.currentPointsField = value;
                    this.RaisePropertyChanged("currentPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idStatus {
            get {
                return this.idStatusField;
            }
            set {
                if ((this.idStatusField.Equals(value) != true)) {
                    this.idStatusField = value;
                    this.RaisePropertyChanged("idStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto {
            get {
                return this.pathPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.pathPhotoField, value) != true)) {
                    this.pathPhotoField = value;
                    this.RaisePropertyChanged("pathPhoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceLobby.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceLobby.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestInviteUsedFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class GuestInviteUsedFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisteredUserAsGuestFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class RegisteredUserAsGuestFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLobby.ILobby", CallbackContract=typeof(ConquiánCliente.ServiceLobby.ILobbyCallback))]
    public interface ILobby {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/GetLobbyState", ReplyAction="http://tempuri.org/ILobby/GetLobbyStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/GetLobbyStateServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        ConquiánCliente.ServiceLobby.LobbyDto GetLobbyState(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/GetLobbyState", ReplyAction="http://tempuri.org/ILobby/GetLobbyStateResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/CreateLobby", ReplyAction="http://tempuri.org/ILobby/CreateLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/CreateLobbyServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        string CreateLobby(int idHostPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/CreateLobby", ReplyAction="http://tempuri.org/ILobby/CreateLobbyResponse")]
        System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribe", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/JoinAndSubscribeServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        bool JoinAndSubscribe(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribe", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeResponse")]
        System.Threading.Tasks.Task<bool> JoinAndSubscribeAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuest", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.GuestInviteUsedFault), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestGuestInviteUsedFaultFault", Name="GuestInviteUsedFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
            "racts")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.RegisteredUserAsGuestFault), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestRegisteredUserAsGuestFaultFault", Name="RegisteredUserAsGuestFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
            "racts")]
        ConquiánCliente.ServiceLobby.PlayerDto JoinAndSubscribeAsGuest(string email, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuest", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.PlayerDto> JoinAndSubscribeAsGuestAsync(string email, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/LeaveAndUnsubscribe")]
        void LeaveAndUnsubscribe(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/LeaveAndUnsubscribe")]
        System.Threading.Tasks.Task LeaveAndUnsubscribeAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SendMessage", ReplyAction="http://tempuri.org/ILobby/SendMessageResponse")]
        void SendMessage(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SendMessage", ReplyAction="http://tempuri.org/ILobby/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SelectGamemode", ReplyAction="http://tempuri.org/ILobby/SelectGamemodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/SelectGamemodeServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void SelectGamemode(string roomCode, int idGamemode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SelectGamemode", ReplyAction="http://tempuri.org/ILobby/SelectGamemodeResponse")]
        System.Threading.Tasks.Task SelectGamemodeAsync(string roomCode, int idGamemode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/StartGame", ReplyAction="http://tempuri.org/ILobby/StartGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/StartGameServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void StartGame(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/StartGame", ReplyAction="http://tempuri.org/ILobby/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/KickPlayer", ReplyAction="http://tempuri.org/ILobby/KickPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConquiánCliente.ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/KickPlayerServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        void KickPlayer(string roomCode, int idRequestingPlayer, int idPlayerToKick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/KickPlayer", ReplyAction="http://tempuri.org/ILobby/KickPlayerResponse")]
        System.Threading.Tasks.Task KickPlayerAsync(string roomCode, int idRequestingPlayer, int idPlayerToKick);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/PlayerJoined")]
        void PlayerJoined(ConquiánCliente.ServiceLobby.PlayerDto newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/PlayerLeft")]
        void PlayerLeft(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/HostLeft")]
        void HostLeft();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/MessageReceived")]
        void MessageReceived(ConquiánCliente.ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/NotifyGamemodeChanged")]
        void NotifyGamemodeChanged(int newGamemodeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/NotifyGameStarting")]
        void NotifyGameStarting();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/YouWereKicked")]
        void YouWereKicked();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyChannel : ConquiánCliente.ServiceLobby.ILobby, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyClient : System.ServiceModel.DuplexClientBase<ConquiánCliente.ServiceLobby.ILobby>, ConquiánCliente.ServiceLobby.ILobby {
        
        public LobbyClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ConquiánCliente.ServiceLobby.LobbyDto GetLobbyState(string roomCode) {
            return base.Channel.GetLobbyState(roomCode);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode) {
            return base.Channel.GetLobbyStateAsync(roomCode);
        }
        
        public string CreateLobby(int idHostPlayer) {
            return base.Channel.CreateLobby(idHostPlayer);
        }
        
        public System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer) {
            return base.Channel.CreateLobbyAsync(idHostPlayer);
        }
        
        public bool JoinAndSubscribe(string roomCode, int idPlayer) {
            return base.Channel.JoinAndSubscribe(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> JoinAndSubscribeAsync(string roomCode, int idPlayer) {
            return base.Channel.JoinAndSubscribeAsync(roomCode, idPlayer);
        }
        
        public ConquiánCliente.ServiceLobby.PlayerDto JoinAndSubscribeAsGuest(string email, string roomCode) {
            return base.Channel.JoinAndSubscribeAsGuest(email, roomCode);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.PlayerDto> JoinAndSubscribeAsGuestAsync(string email, string roomCode) {
            return base.Channel.JoinAndSubscribeAsGuestAsync(email, roomCode);
        }
        
        public void LeaveAndUnsubscribe(string roomCode, int idPlayer) {
            base.Channel.LeaveAndUnsubscribe(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task LeaveAndUnsubscribeAsync(string roomCode, int idPlayer) {
            return base.Channel.LeaveAndUnsubscribeAsync(roomCode, idPlayer);
        }
        
        public void SendMessage(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message) {
            base.Channel.SendMessage(roomCode, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message) {
            return base.Channel.SendMessageAsync(roomCode, message);
        }
        
        public void SelectGamemode(string roomCode, int idGamemode) {
            base.Channel.SelectGamemode(roomCode, idGamemode);
        }
        
        public System.Threading.Tasks.Task SelectGamemodeAsync(string roomCode, int idGamemode) {
            return base.Channel.SelectGamemodeAsync(roomCode, idGamemode);
        }
        
        public void StartGame(string roomCode) {
            base.Channel.StartGame(roomCode);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string roomCode) {
            return base.Channel.StartGameAsync(roomCode);
        }
        
        public void KickPlayer(string roomCode, int idRequestingPlayer, int idPlayerToKick) {
            base.Channel.KickPlayer(roomCode, idRequestingPlayer, idPlayerToKick);
        }
        
        public System.Threading.Tasks.Task KickPlayerAsync(string roomCode, int idRequestingPlayer, int idPlayerToKick) {
            return base.Channel.KickPlayerAsync(roomCode, idRequestingPlayer, idPlayerToKick);
        }
    }
}
