//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.ServiceLobby {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class LobbyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceLobby.MessageDto[] ChatMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquiánCliente.ServiceLobby.PlayerDto[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idHostPlayerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceLobby.MessageDto[] ChatMessages {
            get {
                return this.ChatMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatMessagesField, value) != true)) {
                    this.ChatMessagesField = value;
                    this.RaisePropertyChanged("ChatMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquiánCliente.ServiceLobby.PlayerDto[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode {
            get {
                return this.RoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCodeField, value) != true)) {
                    this.RoomCodeField = value;
                    this.RaisePropertyChanged("RoomCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusLobby {
            get {
                return this.StatusLobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusLobbyField, value) != true)) {
                    this.StatusLobbyField = value;
                    this.RaisePropertyChanged("StatusLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHostPlayer {
            get {
                return this.idHostPlayerField;
            }
            set {
                if ((this.idHostPlayerField.Equals(value) != true)) {
                    this.idHostPlayerField = value;
                    this.RaisePropertyChanged("idHostPlayer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class MessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class PlayerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currentPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathPhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentPoints {
            get {
                return this.currentPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.currentPointsField, value) != true)) {
                    this.currentPointsField = value;
                    this.RaisePropertyChanged("currentPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto {
            get {
                return this.pathPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.pathPhotoField, value) != true)) {
                    this.pathPhotoField = value;
                    this.RaisePropertyChanged("pathPhoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLobby.ILobby")]
    public interface ILobby {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/GetLobbyState", ReplyAction="http://tempuri.org/ILobby/GetLobbyStateResponse")]
        ConquiánCliente.ServiceLobby.LobbyDto GetLobbyState(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/GetLobbyState", ReplyAction="http://tempuri.org/ILobby/GetLobbyStateResponse")]
        System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/CreateLobby", ReplyAction="http://tempuri.org/ILobby/CreateLobbyResponse")]
        string CreateLobby(int idHostPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/CreateLobby", ReplyAction="http://tempuri.org/ILobby/CreateLobbyResponse")]
        System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinLobby", ReplyAction="http://tempuri.org/ILobby/JoinLobbyResponse")]
        bool JoinLobby(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinLobby", ReplyAction="http://tempuri.org/ILobby/JoinLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinLobbyAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/LeaveLobby", ReplyAction="http://tempuri.org/ILobby/LeaveLobbyResponse")]
        void LeaveLobby(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/LeaveLobby", ReplyAction="http://tempuri.org/ILobby/LeaveLobbyResponse")]
        System.Threading.Tasks.Task LeaveLobbyAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SendMessage", ReplyAction="http://tempuri.org/ILobby/SendMessageResponse")]
        void SendMessage(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SendMessage", ReplyAction="http://tempuri.org/ILobby/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyChannel : ConquiánCliente.ServiceLobby.ILobby, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyClient : System.ServiceModel.ClientBase<ConquiánCliente.ServiceLobby.ILobby>, ConquiánCliente.ServiceLobby.ILobby {
        
        public LobbyClient() {
        }
        
        public LobbyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LobbyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConquiánCliente.ServiceLobby.LobbyDto GetLobbyState(string roomCode) {
            return base.Channel.GetLobbyState(roomCode);
        }
        
        public System.Threading.Tasks.Task<ConquiánCliente.ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode) {
            return base.Channel.GetLobbyStateAsync(roomCode);
        }
        
        public string CreateLobby(int idHostPlayer) {
            return base.Channel.CreateLobby(idHostPlayer);
        }
        
        public System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer) {
            return base.Channel.CreateLobbyAsync(idHostPlayer);
        }
        
        public bool JoinLobby(string roomCode, int idPlayer) {
            return base.Channel.JoinLobby(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> JoinLobbyAsync(string roomCode, int idPlayer) {
            return base.Channel.JoinLobbyAsync(roomCode, idPlayer);
        }
        
        public void LeaveLobby(string roomCode, int idPlayer) {
            base.Channel.LeaveLobby(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task LeaveLobbyAsync(string roomCode, int idPlayer) {
            return base.Channel.LeaveLobbyAsync(roomCode, idPlayer);
        }
        
        public void SendMessage(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message) {
            base.Channel.SendMessage(roomCode, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string roomCode, ConquiánCliente.ServiceLobby.MessageDto message) {
            return base.Channel.SendMessageAsync(roomCode, message);
        }
    }
}
