//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquiánCliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear o unirse.
        /// </summary>
        public static string CreateOrJoin {
            get {
                return ResourceManager.GetString("CreateOrJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditDataEdit {
            get {
                return ResourceManager.GetString("EditDataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar información.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor: {0}.
        /// </summary>
        public static string ErrorConnectingToServer {
            get {
                return ResourceManager.GetString("ErrorConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no puede estar vacío..
        /// </summary>
        public static string ErrorEmailEmpty {
            get {
                return ResourceManager.GetString("ErrorEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del correo electrónico no es válido..
        /// </summary>
        public static string ErrorEmailInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no debe exceder los {0} caracteres..
        /// </summary>
        public static string ErrorEmailLenght {
            get {
                return ResourceManager.GetString("ErrorEmailLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de sala no puede estar vacío.
        /// </summary>
        public static string ErrorEmptyRoomCode {
            get {
                return ResourceManager.GetString("ErrorEmptyRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales inválidas. Por favor, verifique su correo y contraseña..
        /// </summary>
        public static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al entrar a la sala.
        /// </summary>
        public static string ErrorJoinLobby {
            get {
                return ResourceManager.GetString("ErrorJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede estar vacío..
        /// </summary>
        public static string ErrorLastNameEmpty {
            get {
                return ResourceManager.GetString("ErrorLastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido solo puede contener letras y espacios..
        /// </summary>
        public static string ErrorLastNameInvalidChars {
            get {
                return ResourceManager.GetString("ErrorLastNameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorLastNameLength {
            get {
                return ResourceManager.GetString("ErrorLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al crear la sala.
        /// </summary>
        public static string ErrorLobbyCreation {
            get {
                return ResourceManager.GetString("ErrorLobbyCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede estar vacío..
        /// </summary>
        public static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorNameLength {
            get {
                return ResourceManager.GetString("ErrorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede estar vacío..
        /// </summary>
        public static string ErrorNicknameEmpty {
            get {
                return ResourceManager.GetString("ErrorNicknameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo puede contener letras y números..
        /// </summary>
        public static string ErrorNicknameInvalidChars {
            get {
                return ResourceManager.GetString("ErrorNicknameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorNicknameLength {
            get {
                return ResourceManager.GetString("ErrorNicknameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía..
        /// </summary>
        public static string ErrorPasswordEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener entre {0} y {1} caracteres..
        /// </summary>
        public static string ErrorPasswordLength {
            get {
                return ResourceManager.GetString("ErrorPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede tener espacios.
        /// </summary>
        public static string ErrorPasswordNoSpaces {
            get {
                return ResourceManager.GetString("ErrorPasswordNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos un carácter especial..
        /// </summary>
        public static string ErrorPasswordNoSpecialChar {
            get {
                return ResourceManager.GetString("ErrorPasswordNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos una mayúscula..
        /// </summary>
        public static string ErrorPasswordNoUppercase {
            get {
                return ResourceManager.GetString("ErrorPasswordNoUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo registrar. El correo o nombre de usuario ya podrían estar en uso..
        /// </summary>
        public static string ErrorRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje no se pudo enviar.
        /// </summary>
        public static string ErrorSendMessageFailed {
            get {
                return ResourceManager.GetString("ErrorSendMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor no disponible..
        /// </summary>
        public static string ErrorServerUnavailable {
            get {
                return ResourceManager.GetString("ErrorServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado: {0}.
        /// </summary>
        public static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la imagen de perfil..
        /// </summary>
        public static string ErrorUpdatePhoto {
            get {
                return ResourceManager.GetString("ErrorUpdatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo puede contener letras y espacios..
        /// </summary>
        public static string ErrorValidName {
            get {
                return ResourceManager.GetString("ErrorValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación no puede estar vacio.
        /// </summary>
        public static string ErrorVerificationCodeEmpty {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación es incorrecto..
        /// </summary>
        public static string ErrorVerificationCodeIncorrect {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo de verificación..
        /// </summary>
        public static string ErrorVerificationEmail {
            get {
                return ResourceManager.GetString("ErrorVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendList {
            get {
                return ResourceManager.GetString("FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones .
        /// </summary>
        public static string FriendListAccions {
            get {
                return ResourceManager.GetString("FriendListAccions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string FriendListAdd {
            get {
                return ResourceManager.GetString("FriendListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea eliminarlo de su lista de amigos?.
        /// </summary>
        public static string FriendListDeleteConfirmation {
            get {
                return ResourceManager.GetString("FriendListDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar amigo.
        /// </summary>
        public static string FriendListDeletedError {
            get {
                return ResourceManager.GetString("FriendListDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo eliminado correctamente.
        /// </summary>
        public static string FriendListDeletedSuccess {
            get {
                return ResourceManager.GetString("FriendListDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string FriendListRequests {
            get {
                return ResourceManager.GetString("FriendListRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string FriendListSearch {
            get {
                return ResourceManager.GetString("FriendListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil .
        /// </summary>
        public static string FriendListViewProfile {
            get {
                return ResourceManager.GetString("FriendListViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar a partida.
        /// </summary>
        public static string FriendOptionsInviteMatch {
            get {
                return ResourceManager.GetString("FriendOptionsInviteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver pérfil.
        /// </summary>
        public static string FriendOptionsViewProfile {
            get {
                return ResourceManager.GetString("FriendOptionsViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil de amigo.
        /// </summary>
        public static string FriendProfile {
            get {
                return ResourceManager.GetString("FriendProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string FriendRequestsDecline {
            get {
                return ResourceManager.GetString("FriendRequestsDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar solicitud de amistad.
        /// </summary>
        public static string FriendRequestSentError {
            get {
                return ResourceManager.GetString("FriendRequestSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad enviada correctamente .
        /// </summary>
        public static string FriendRequestSentSuccess {
            get {
                return ResourceManager.GetString("FriendRequestSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string FriendsOptionsDelete {
            get {
                return ResourceManager.GetString("FriendsOptionsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string FrienListStatus {
            get {
                return ResourceManager.GetString("FrienListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalAccept {
            get {
                return ResourceManager.GetString("GlobalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        public static string GlobalBack {
            get {
                return ResourceManager.GetString("GlobalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string GlobalConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string GlobalEmail {
            get {
                return ResourceManager.GetString("GlobalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string GlobalGuess {
            get {
                return ResourceManager.GetString("GlobalGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string GlobalInvite {
            get {
                return ResourceManager.GetString("GlobalInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string GlobalLanguage {
            get {
                return ResourceManager.GetString("GlobalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido(s).
        /// </summary>
        public static string GlobalLastName {
            get {
                return ResourceManager.GetString("GlobalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string GlobalLevel {
            get {
                return ResourceManager.GetString("GlobalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string GlobalLogIn {
            get {
                return ResourceManager.GetString("GlobalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string GlobalName {
            get {
                return ResourceManager.GetString("GlobalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string GlobalNickname {
            get {
                return ResourceManager.GetString("GlobalNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a o.
        /// </summary>
        public static string GlobalOr {
            get {
                return ResourceManager.GetString("GlobalOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string GlobalPassword {
            get {
                return ResourceManager.GetString("GlobalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        public static string GlobalPasswordRecovery {
            get {
                return ResourceManager.GetString("GlobalPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string GlobalSignUp {
            get {
                return ResourceManager.GetString("GlobalSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes.
        /// </summary>
        public static string GlobalSocial {
            get {
                return ResourceManager.GetString("GlobalSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        public static string GlobalVerificationCode {
            get {
                return ResourceManager.GetString("GlobalVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string GlobalViewProfile {
            get {
                return ResourceManager.GetString("GlobalViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derrota.
        /// </summary>
        public static string HistoryDefeat {
            get {
                return ResourceManager.GetString("HistoryDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victoria.
        /// </summary>
        public static string HistoryVictory {
            get {
                return ResourceManager.GetString("HistoryVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El host ha salido de la sala.
        /// </summary>
        public static string InfoHostLeft {
            get {
                return ResourceManager.GetString("InfoHostLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la información .
        /// </summary>
        public static string InfoUpdateFailed {
            get {
                return ResourceManager.GetString("InfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada correctamente.
        /// </summary>
        public static string InfoUpdateSuccess {
            get {
                return ResourceManager.GetString("InfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego clásico.
        /// </summary>
        public static string LobbyClassicGame {
            get {
                return ResourceManager.GetString("LobbyClassicGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string LobbyCreateRoom {
            get {
                return ResourceManager.GetString("LobbyCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string LobbyGameMode {
            get {
                return ResourceManager.GetString("LobbyGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string LobbyHostPrefix {
            get {
                return ResourceManager.GetString("LobbyHostPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a la sala.
        /// </summary>
        public static string LobbyJoinRoom {
            get {
                return ResourceManager.GetString("LobbyJoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse por código.
        /// </summary>
        public static string LobbyJoinWithCode {
            get {
                return ResourceManager.GetString("LobbyJoinWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string LobbyKick {
            get {
                return ResourceManager.GetString("LobbyKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego rápido.
        /// </summary>
        public static string LobbyQuickGame {
            get {
                return ResourceManager.GetString("LobbyQuickGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string LobbyReady {
            get {
                return ResourceManager.GetString("LobbyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala.
        /// </summary>
        public static string LobbyRoomCode {
            get {
                return ResourceManager.GetString("LobbyRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar juego.
        /// </summary>
        public static string LobbyStartGame {
            get {
                return ResourceManager.GetString("LobbyStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string LogInAsGuess {
            get {
                return ResourceManager.GetString("LogInAsGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LogInForgotPassword {
            get {
                return ResourceManager.GetString("LogInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenuFriends {
            get {
                return ResourceManager.GetString("MainMenuFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string MainMenuPlay {
            get {
                return ResourceManager.GetString("MainMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string PasswordRecoveryNewPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        public static string PasswordRecoveryResetPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string PasswordRecoverySend {
            get {
                return ResourceManager.GetString("PasswordRecoverySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string ProfileChange {
            get {
                return ResourceManager.GetString("ProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar imagen de perfil .
        /// </summary>
        public static string ProfileEditPicture {
            get {
                return ResourceManager.GetString("ProfileEditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el código de verificación enviado a tu correo..
        /// </summary>
        public static string RecoveryCodeInfo {
            get {
                return ResourceManager.GetString("RecoveryCodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico para enviarte un código de verificación..
        /// </summary>
        public static string RecoveryInfo {
            get {
                return ResourceManager.GetString("RecoveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada exitosamente! Por favor, inicie sesión..
        /// </summary>
        public static string SuccessAccountCreated {
            get {
                return ResourceManager.GetString("SuccessAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Autenticación.
        /// </summary>
        public static string TitleAuthenticationError {
            get {
                return ResourceManager.GetString("TitleAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación .
        /// </summary>
        public static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Conexión.
        /// </summary>
        public static string TitleConnectionError {
            get {
                return ResourceManager.GetString("TitleConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Completo.
        /// </summary>
        public static string TitleRegistrationComplete {
            get {
                return ResourceManager.GetString("TitleRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Registro.
        /// </summary>
        public static string TitleRegistrationError {
            get {
                return ResourceManager.GetString("TitleRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito .
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string TitleValidation {
            get {
                return ResourceManager.GetString("TitleValidation", resourceCulture);
            }
        }
    }
}
