//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquiánCliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditDataEdit {
            get {
                return ResourceManager.GetString("EditDataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar información.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string FriendListAdd {
            get {
                return ResourceManager.GetString("FriendListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes.
        /// </summary>
        public static string FriendListRequests {
            get {
                return ResourceManager.GetString("FriendListRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string FriendListSearch {
            get {
                return ResourceManager.GetString("FriendListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar a partida.
        /// </summary>
        public static string FriendOptionsInviteMatch {
            get {
                return ResourceManager.GetString("FriendOptionsInviteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver pérfil.
        /// </summary>
        public static string FriendOptionsViewProfile {
            get {
                return ResourceManager.GetString("FriendOptionsViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string FriendsOptionsDelete {
            get {
                return ResourceManager.GetString("FriendsOptionsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string GlobalAccept {
            get {
                return ResourceManager.GetString("GlobalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        public static string GlobalBack {
            get {
                return ResourceManager.GetString("GlobalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string GlobalConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string GlobalEmail {
            get {
                return ResourceManager.GetString("GlobalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitado.
        /// </summary>
        public static string GlobalGuess {
            get {
                return ResourceManager.GetString("GlobalGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar.
        /// </summary>
        public static string GlobalInvite {
            get {
                return ResourceManager.GetString("GlobalInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string GlobalLanguage {
            get {
                return ResourceManager.GetString("GlobalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido(s).
        /// </summary>
        public static string GlobalLastName {
            get {
                return ResourceManager.GetString("GlobalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string GlobalLevel {
            get {
                return ResourceManager.GetString("GlobalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string GlobalLogIn {
            get {
                return ResourceManager.GetString("GlobalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string GlobalName {
            get {
                return ResourceManager.GetString("GlobalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string GlobalNickname {
            get {
                return ResourceManager.GetString("GlobalNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string GlobalPassword {
            get {
                return ResourceManager.GetString("GlobalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string GlobalPasswordRecovery {
            get {
                return ResourceManager.GetString("GlobalPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string GlobalSignUp {
            get {
                return ResourceManager.GetString("GlobalSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes.
        /// </summary>
        public static string GlobalSocial {
            get {
                return ResourceManager.GetString("GlobalSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación.
        /// </summary>
        public static string GlobalVerificationCode {
            get {
                return ResourceManager.GetString("GlobalVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver perfil.
        /// </summary>
        public static string GlobalViewProfile {
            get {
                return ResourceManager.GetString("GlobalViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derrota.
        /// </summary>
        public static string HistoryDefeat {
            get {
                return ResourceManager.GetString("HistoryDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victoria.
        /// </summary>
        public static string HistoryVictory {
            get {
                return ResourceManager.GetString("HistoryVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juego clásico.
        /// </summary>
        public static string LobbyClassicGame {
            get {
                return ResourceManager.GetString("LobbyClassicGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de juego.
        /// </summary>
        public static string LobbyGameMode {
            get {
                return ResourceManager.GetString("LobbyGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsar.
        /// </summary>
        public static string LobbyKick {
            get {
                return ResourceManager.GetString("LobbyKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juego rápido.
        /// </summary>
        public static string LobbyQuickGame {
            get {
                return ResourceManager.GetString("LobbyQuickGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string LobbyReady {
            get {
                return ResourceManager.GetString("LobbyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empezar juego.
        /// </summary>
        public static string LobbyStartGame {
            get {
                return ResourceManager.GetString("LobbyStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        public static string LogInAsGuess {
            get {
                return ResourceManager.GetString("LogInAsGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LogInForgotPassword {
            get {
                return ResourceManager.GetString("LogInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar.
        /// </summary>
        public static string MainMenuPlay {
            get {
                return ResourceManager.GetString("MainMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string PasswordRecoveryNewPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string PasswordRecoveryResetPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string PasswordRecoverySend {
            get {
                return ResourceManager.GetString("PasswordRecoverySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        public static string ProfileChange {
            get {
                return ResourceManager.GetString("ProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar imagen de perfil .
        /// </summary>
        public static string ProfileEditPicture {
            get {
                return ResourceManager.GetString("ProfileEditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el código de verificación enviado a tu correo..
        /// </summary>
        public static string RecoveryInfo {
            get {
                return ResourceManager.GetString("RecoveryInfo", resourceCulture);
            }
        }
    }
}
