//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquiánCliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que quieres expulsar a este jugador?.
        /// </summary>
        public static string ConfirmKickPlayer {
            get {
                return ResourceManager.GetString("ConfirmKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear o unirse.
        /// </summary>
        public static string CreateOrJoin {
            get {
                return ResourceManager.GetString("CreateOrJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditDataEdit {
            get {
                return ResourceManager.GetString("EditDataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar información.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has tomado una carta del mazo en este turno..
        /// </summary>
        public static string ErrorAlreadyDrawn {
            get {
                return ResourceManager.GetString("ErrorAlreadyDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicación con el servidor..
        /// </summary>
        public static string ErrorCommunicationError {
            get {
                return ResourceManager.GetString("ErrorCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor: {0}.
        /// </summary>
        public static string ErrorConnectingToServer {
            get {
                return ResourceManager.GetString("ErrorConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mazo vacío. .
        /// </summary>
        public static string ErrorDeckEmpty {
            get {
                return ResourceManager.GetString("ErrorDeckEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no puede estar vacío..
        /// </summary>
        public static string ErrorEmailEmpty {
            get {
                return ResourceManager.GetString("ErrorEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya existe.
        /// </summary>
        public static string ErrorEmailExists {
            get {
                return ResourceManager.GetString("ErrorEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del correo electrónico no es válido..
        /// </summary>
        public static string ErrorEmailInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no debe exceder los {0} caracteres..
        /// </summary>
        public static string ErrorEmailLenght {
            get {
                return ResourceManager.GetString("ErrorEmailLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarte vacío..
        /// </summary>
        public static string ErrorEmptyDiscaard {
            get {
                return ResourceManager.GetString("ErrorEmptyDiscaard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de sala no puede estar vacío.
        /// </summary>
        public static string ErrorEmptyRoomCode {
            get {
                return ResourceManager.GetString("ErrorEmptyRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una solicitud pendiente o una amistad con este jugador..
        /// </summary>
        public static string ErrorExistingRequest {
            get {
                return ResourceManager.GetString("ErrorExistingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el juego..
        /// </summary>
        public static string ErrorGame {
            get {
                return ResourceManager.GetString("ErrorGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado un modo de juego.
        /// </summary>
        public static string ErrorGamemodeNotSelected {
            get {
                return ResourceManager.GetString("ErrorGamemodeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El movimiento intentado no es válido..
        /// </summary>
        public static string ErrorGameRuleViolation {
            get {
                return ResourceManager.GetString("ErrorGameRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error: .
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La invitación no es válida o la sala ya no está disponible..
        /// </summary>
        public static string ErrorGuestInviteMismatch {
            get {
                return ResourceManager.GetString("ErrorGuestInviteMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión no encontrado..
        /// </summary>
        public static string ErrorHostUserNotFound {
            get {
                return ResourceManager.GetString("ErrorHostUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes tomar esta carta ahora..
        /// </summary>
        public static string ErrorInvalidCardAction {
            get {
                return ResourceManager.GetString("ErrorInvalidCardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales inválidas. Por favor, verifique su correo y contraseña..
        /// </summary>
        public static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las jugadas deben de tener al menos 3 cartas validas..
        /// </summary>
        public static string ErrorInvalidMeld {
            get {
                return ResourceManager.GetString("ErrorInvalidMeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de nombre invalido..
        /// </summary>
        public static string ErrorInvalidNameFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de contraseña invalido..
        /// </summary>
        public static string ErrorInvalidPasswordFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código introducido es incorrecto..
        /// </summary>
        public static string ErrorInvalidVerificationCode {
            get {
                return ResourceManager.GetString("ErrorInvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al entrar a la sala.
        /// </summary>
        public static string ErrorJoinLobby {
            get {
                return ResourceManager.GetString("ErrorJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede estar vacío..
        /// </summary>
        public static string ErrorLastNameEmpty {
            get {
                return ResourceManager.GetString("ErrorLastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido solo puede contener letras y espacios..
        /// </summary>
        public static string ErrorLastNameInvalidChars {
            get {
                return ResourceManager.GetString("ErrorLastNameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorLastNameLength {
            get {
                return ResourceManager.GetString("ErrorLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar la acción solicitada. Por favor, intente de nuevo..
        /// </summary>
        public static string ErrorLobbyAction {
            get {
                return ResourceManager.GetString("ErrorLobbyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al crear la sala.
        /// </summary>
        public static string ErrorLobbyCreation {
            get {
                return ResourceManager.GetString("ErrorLobbyCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala está llena o en juego..
        /// </summary>
        public static string ErrorLobbyFull {
            get {
                return ResourceManager.GetString("ErrorLobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el lobby..
        /// </summary>
        public static string ErrorLobbyNotFound {
            get {
                return ResourceManager.GetString("ErrorLobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cerrar sesión..
        /// </summary>
        public static string ErrorLogOutSession {
            get {
                return ResourceManager.GetString("ErrorLogOutSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes pagar una carta para terminar..
        /// </summary>
        public static string ErrorMustDiscardToFinish {
            get {
                return ResourceManager.GetString("ErrorMustDiscardToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede estar vacío..
        /// </summary>
        public static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorNameLength {
            get {
                return ResourceManager.GetString("ErrorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede estar vacío..
        /// </summary>
        public static string ErrorNicknameEmpty {
            get {
                return ResourceManager.GetString("ErrorNicknameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya existe.
        /// </summary>
        public static string ErrorNicknameExists {
            get {
                return ResourceManager.GetString("ErrorNicknameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo puede contener letras y números..
        /// </summary>
        public static string ErrorNicknameInvalidChars {
            get {
                return ResourceManager.GetString("ErrorNicknameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede tener más de {0} caracteres..
        /// </summary>
        public static string ErrorNicknameLength {
            get {
                return ResourceManager.GetString("ErrorNicknameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe haber al menos dos jugadores para iniciar la partida..
        /// </summary>
        public static string ErrorNotEnoughPlayers {
            get {
                return ResourceManager.GetString("ErrorNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No encontrado..
        /// </summary>
        public static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes expulsarte a ti mismo..
        /// </summary>
        public static string ErrorNotKickYourSelf {
            get {
                return ResourceManager.GetString("ErrorNotKickYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes expulsar debido a que no eres el host..
        /// </summary>
        public static string ErrorNotLobbyHost {
            get {
                return ResourceManager.GetString("ErrorNotLobbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es tu turno para realizar esta acción..
        /// </summary>
        public static string ErrorNotYourTurn {
            get {
                return ResourceManager.GetString("ErrorNotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo la operación en el servidor..
        /// </summary>
        public static string ErrorOperationFailed {
            get {
                return ResourceManager.GetString("ErrorOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía..
        /// </summary>
        public static string ErrorPasswordEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener entre {0} y {1} caracteres..
        /// </summary>
        public static string ErrorPasswordLength {
            get {
                return ResourceManager.GetString("ErrorPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede tener espacios.
        /// </summary>
        public static string ErrorPasswordNoSpaces {
            get {
                return ResourceManager.GetString("ErrorPasswordNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos un carácter especial..
        /// </summary>
        public static string ErrorPasswordNoSpecialChar {
            get {
                return ResourceManager.GetString("ErrorPasswordNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos una mayúscula..
        /// </summary>
        public static string ErrorPasswordNoUppercase {
            get {
                return ResourceManager.GetString("ErrorPasswordNoUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo reiniciar la contraseña. Es posible que el código haya expirado. Intente de nuevo..
        /// </summary>
        public static string ErrorPasswordResetFailed {
            get {
                return ResourceManager.GetString("ErrorPasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes decidir sobre la carta del descarte primero (Tomar o Pasar)..
        /// </summary>
        public static string ErrorPendingDiscardAction {
            get {
                return ResourceManager.GetString("ErrorPendingDiscardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo procesar la solicitud. Verifique que el correo esté registrado y verificado..
        /// </summary>
        public static string ErrorRecoveryRequestFailed {
            get {
                return ResourceManager.GetString("ErrorRecoveryRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya está registrado, por favor inicie sesión.
        /// </summary>
        public static string ErrorRegisteredMail {
            get {
                return ResourceManager.GetString("ErrorRegisteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo registrar. El correo o nombre de usuario ya podrían estar en uso..
        /// </summary>
        public static string ErrorRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de sala no puede estar vacío..
        /// </summary>
        public static string ErrorRoomCodeEmpty {
            get {
                return ResourceManager.GetString("ErrorRoomCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de sala debe tener 5 caracteres..
        /// </summary>
        public static string ErrorRoomCodeLength {
            get {
                return ResourceManager.GetString("ErrorRoomCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al seleccionar el modo de juego..
        /// </summary>
        public static string ErrorSelectGameMode {
            get {
                return ResourceManager.GetString("ErrorSelectGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje no se pudo enviar.
        /// </summary>
        public static string ErrorSendMessageFailed {
            get {
                return ResourceManager.GetString("ErrorSendMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno del servidor..
        /// </summary>
        public static string ErrorServerInternalError {
            get {
                return ResourceManager.GetString("ErrorServerInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor no disponible..
        /// </summary>
        public static string ErrorServerUnavailable {
            get {
                return ResourceManager.GetString("ErrorServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya cuenta con una sesión activa, por favor cierre la sesión activa para poder abrir una nueva.
        /// </summary>
        public static string ErrorSessionActive {
            get {
                return ResourceManager.GetString("ErrorSessionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar el juego.
        /// </summary>
        public static string ErrorStartingGame {
            get {
                return ResourceManager.GetString("ErrorStartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: La operación tardó demasiado tiempo..
        /// </summary>
        public static string ErrorTimeout {
            get {
                return ResourceManager.GetString("ErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado: {0}.
        /// </summary>
        public static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la imagen de perfil..
        /// </summary>
        public static string ErrorUpdatePhoto {
            get {
                return ResourceManager.GetString("ErrorUpdatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta invitación ya ha sido utilizada..
        /// </summary>
        public static string ErrorUsedInvitation {
            get {
                return ResourceManager.GetString("ErrorUsedInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no fue encontrado.
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con una invitación..
        /// </summary>
        public static string ErrorValidationFailed {
            get {
                return ResourceManager.GetString("ErrorValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo puede contener letras y espacios..
        /// </summary>
        public static string ErrorValidName {
            get {
                return ResourceManager.GetString("ErrorValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación no puede estar vacio.
        /// </summary>
        public static string ErrorVerificationCodeEmpty {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación ha expirado..
        /// </summary>
        public static string ErrorVerificationCodeExpired {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación es incorrecto..
        /// </summary>
        public static string ErrorVerificationCodeIncorrect {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo de verificación..
        /// </summary>
        public static string ErrorVerificationEmail {
            get {
                return ResourceManager.GetString("ErrorVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el viewmodel del juego..
        /// </summary>
        public static string ErrorViewModel {
            get {
                return ResourceManager.GetString("ErrorViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendList {
            get {
                return ResourceManager.GetString("FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones .
        /// </summary>
        public static string FriendListAccions {
            get {
                return ResourceManager.GetString("FriendListAccions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string FriendListAdd {
            get {
                return ResourceManager.GetString("FriendListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea eliminarlo de su lista de amigos?.
        /// </summary>
        public static string FriendListDeleteConfirmation {
            get {
                return ResourceManager.GetString("FriendListDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar amigo.
        /// </summary>
        public static string FriendListDeletedError {
            get {
                return ResourceManager.GetString("FriendListDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo eliminado correctamente.
        /// </summary>
        public static string FriendListDeletedSuccess {
            get {
                return ResourceManager.GetString("FriendListDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string FriendListRequests {
            get {
                return ResourceManager.GetString("FriendListRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string FriendListSearch {
            get {
                return ResourceManager.GetString("FriendListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil .
        /// </summary>
        public static string FriendListViewProfile {
            get {
                return ResourceManager.GetString("FriendListViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar a partida.
        /// </summary>
        public static string FriendOptionsInviteMatch {
            get {
                return ResourceManager.GetString("FriendOptionsInviteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver pérfil.
        /// </summary>
        public static string FriendOptionsViewProfile {
            get {
                return ResourceManager.GetString("FriendOptionsViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil de amigo.
        /// </summary>
        public static string FriendProfile {
            get {
                return ResourceManager.GetString("FriendProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string FriendRequestsDecline {
            get {
                return ResourceManager.GetString("FriendRequestsDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar solicitud de amistad.
        /// </summary>
        public static string FriendRequestSentError {
            get {
                return ResourceManager.GetString("FriendRequestSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad enviada correctamente .
        /// </summary>
        public static string FriendRequestSentSuccess {
            get {
                return ResourceManager.GetString("FriendRequestSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string FriendsOptionsDelete {
            get {
                return ResourceManager.GetString("FriendsOptionsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string FrienListStatus {
            get {
                return ResourceManager.GetString("FrienListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú principal.
        /// </summary>
        public static string GameBackToMainMenu {
            get {
                return ResourceManager.GetString("GameBackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derrota.
        /// </summary>
        public static string GameDefeat {
            get {
                return ResourceManager.GetString("GameDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo puedes descartar una carta para pagar después de bajar juego.
        ///Si la carta no te sirve, usa el botón &apos;Pasar&apos;..
        /// </summary>
        public static string GameDiscardRestriction {
            get {
                return ResourceManager.GetString("GameDiscardRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastra tu jugada aquí.
        /// </summary>
        public static string GameDropZone {
            get {
                return ResourceManager.GetString("GameDropZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string GameExit {
            get {
                return ResourceManager.GetString("GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego inválido.
        /// </summary>
        public static string GameInvalidMeld {
            get {
                return ResourceManager.GetString("GameInvalidMeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para tomar esta carta, selecciona al menos 2 cartas de tu mano que formen una tercia o corrida..
        /// </summary>
        public static string GameInvalidMove {
            get {
                return ResourceManager.GetString("GameInvalidMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de que quieres salir de la partida? .
        /// </summary>
        public static string GameLeaveTheMatch {
            get {
                return ResourceManager.GetString("GameLeaveTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Jugada realizada!
        ///Ahora debes pagar una carta de tu mano para terminar tu turno..
        /// </summary>
        public static string GameMoveMade {
            get {
                return ResourceManager.GetString("GameMoveMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oponente.
        /// </summary>
        public static string GameOpponent {
            get {
                return ResourceManager.GetString("GameOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El oponente ha abandonado la partida..
        /// </summary>
        public static string GameOpponentLeft {
            get {
                return ResourceManager.GetString("GameOpponentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno del oponente .
        /// </summary>
        public static string GameOpponentsturn {
            get {
                return ResourceManager.GetString("GameOpponentsturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string GamePlayer {
            get {
                return ResourceManager.GetString("GamePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados .
        /// </summary>
        public static string GameResultsTitle {
            get {
                return ResourceManager.GetString("GameResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al juego .
        /// </summary>
        public static string GameReturnToGame {
            get {
                return ResourceManager.GetString("GameReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para cambiar la carta, selecciona 1 carta de tu mano.
        ///Para bajar juego, selecciona 2 o más..
        /// </summary>
        public static string GameSwapInstruction {
            get {
                return ResourceManager.GetString("GameSwapInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo 00:00.
        /// </summary>
        public static string GameTime {
            get {
                return ResourceManager.GetString("GameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasar.
        /// </summary>
        public static string GameToPass {
            get {
                return ResourceManager.GetString("GameToPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu turno.
        /// </summary>
        public static string GameTurn {
            get {
                return ResourceManager.GetString("GameTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victoria.
        /// </summary>
        public static string GameVictory {
            get {
                return ResourceManager.GetString("GameVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalAccept {
            get {
                return ResourceManager.GetString("GlobalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        public static string GlobalBack {
            get {
                return ResourceManager.GetString("GlobalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string GlobalConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string GlobalEmail {
            get {
                return ResourceManager.GetString("GlobalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string GlobalGuess {
            get {
                return ResourceManager.GetString("GlobalGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string GlobalInvite {
            get {
                return ResourceManager.GetString("GlobalInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string GlobalLanguage {
            get {
                return ResourceManager.GetString("GlobalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido(s).
        /// </summary>
        public static string GlobalLastName {
            get {
                return ResourceManager.GetString("GlobalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string GlobalLevel {
            get {
                return ResourceManager.GetString("GlobalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string GlobalLoading {
            get {
                return ResourceManager.GetString("GlobalLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string GlobalLogIn {
            get {
                return ResourceManager.GetString("GlobalLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string GlobalName {
            get {
                return ResourceManager.GetString("GlobalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string GlobalNickname {
            get {
                return ResourceManager.GetString("GlobalNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a o.
        /// </summary>
        public static string GlobalOr {
            get {
                return ResourceManager.GetString("GlobalOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string GlobalPassword {
            get {
                return ResourceManager.GetString("GlobalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        public static string GlobalPasswordRecovery {
            get {
                return ResourceManager.GetString("GlobalPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string GlobalPoints {
            get {
                return ResourceManager.GetString("GlobalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string GlobalSignUp {
            get {
                return ResourceManager.GetString("GlobalSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el correo, vuelve a intentarlo más tarde.
        /// </summary>
        public static string GlobalSmtpError {
            get {
                return ResourceManager.GetString("GlobalSmtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes.
        /// </summary>
        public static string GlobalSocial {
            get {
                return ResourceManager.GetString("GlobalSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la base de datos.
        /// </summary>
        public static string GlobalSqlError {
            get {
                return ResourceManager.GetString("GlobalSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        public static string GlobalVerificationCode {
            get {
                return ResourceManager.GetString("GlobalVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string GlobalViewProfile {
            get {
                return ResourceManager.GetString("GlobalViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derrota.
        /// </summary>
        public static string HistoryDefeat {
            get {
                return ResourceManager.GetString("HistoryDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victoria.
        /// </summary>
        public static string HistoryVictory {
            get {
                return ResourceManager.GetString("HistoryVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El anfitrión ha salido de la sala.
        /// </summary>
        public static string InfoHostLeft {
            get {
                return ResourceManager.GetString("InfoHostLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la información .
        /// </summary>
        public static string InfoUpdateFailed {
            get {
                return ResourceManager.GetString("InfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada correctamente.
        /// </summary>
        public static string InfoUpdateSuccess {
            get {
                return ResourceManager.GetString("InfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido expulsado de la sala por el anfitrión..
        /// </summary>
        public static string InfoYouWereKicked {
            get {
                return ResourceManager.GetString("InfoYouWereKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego clásico.
        /// </summary>
        public static string LobbyClassicGame {
            get {
                return ResourceManager.GetString("LobbyClassicGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string LobbyCreateRoom {
            get {
                return ResourceManager.GetString("LobbyCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al invitar .
        /// </summary>
        public static string LobbyErrorInvitationFailed {
            get {
                return ResourceManager.GetString("LobbyErrorInvitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la lista de amigos.
        /// </summary>
        public static string LobbyErrorLoadingFriends {
            get {
                return ResourceManager.GetString("LobbyErrorLoadingFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala llena.
        /// </summary>
        public static string LobbyFull {
            get {
                return ResourceManager.GetString("LobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string LobbyGameMode {
            get {
                return ResourceManager.GetString("LobbyGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada.
        /// </summary>
        public static string LobbyGuestInviteSent {
            get {
                return ResourceManager.GetString("LobbyGuestInviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string LobbyHostPrefix {
            get {
                return ResourceManager.GetString("LobbyHostPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación.
        /// </summary>
        public static string LobbyInvitation {
            get {
                return ResourceManager.GetString("LobbyInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada .
        /// </summary>
        public static string LobbyInvitationSent {
            get {
                return ResourceManager.GetString("LobbyInvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a te ha invitado a una partida.
        /// </summary>
        public static string LobbyInvitedYou {
            get {
                return ResourceManager.GetString("LobbyInvitedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a la sala.
        /// </summary>
        public static string LobbyJoinRoom {
            get {
                return ResourceManager.GetString("LobbyJoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse por código.
        /// </summary>
        public static string LobbyJoinWithCode {
            get {
                return ResourceManager.GetString("LobbyJoinWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string LobbyKick {
            get {
                return ResourceManager.GetString("LobbyKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego rápido.
        /// </summary>
        public static string LobbyQuickGame {
            get {
                return ResourceManager.GetString("LobbyQuickGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string LobbyReady {
            get {
                return ResourceManager.GetString("LobbyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar .
        /// </summary>
        public static string LobbyReject {
            get {
                return ResourceManager.GetString("LobbyReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala.
        /// </summary>
        public static string LobbyRoomCode {
            get {
                return ResourceManager.GetString("LobbyRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código de sala .
        /// </summary>
        public static string LobbySendRoomCode {
            get {
                return ResourceManager.GetString("LobbySendRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar juego.
        /// </summary>
        public static string LobbyStartGame {
            get {
                return ResourceManager.GetString("LobbyStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string LogInAsGuess {
            get {
                return ResourceManager.GetString("LogInAsGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LogInForgotPassword {
            get {
                return ResourceManager.GetString("LogInForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenuFriends {
            get {
                return ResourceManager.GetString("MainMenuFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string MainMenuPlay {
            get {
                return ResourceManager.GetString("MainMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string PasswordRecoveryNewPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        public static string PasswordRecoveryResetPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string PasswordRecoverySend {
            get {
                return ResourceManager.GetString("PasswordRecoverySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string ProfileChange {
            get {
                return ResourceManager.GetString("ProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar imagen de perfil .
        /// </summary>
        public static string ProfileEditPicture {
            get {
                return ResourceManager.GetString("ProfileEditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el código de verificación enviado a tu correo..
        /// </summary>
        public static string RecoveryCodeInfo {
            get {
                return ResourceManager.GetString("RecoveryCodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico para enviarte un código de verificación..
        /// </summary>
        public static string RecoveryInfo {
            get {
                return ResourceManager.GetString("RecoveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectado.
        /// </summary>
        public static string StatusOffline {
            get {
                return ResourceManager.GetString("StatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En linea .
        /// </summary>
        public static string StatusOnline {
            get {
                return ResourceManager.GetString("StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada exitosamente! Por favor, inicie sesión..
        /// </summary>
        public static string SuccessAccountCreated {
            get {
                return ResourceManager.GetString("SuccessAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada con éxito. Ya puedes iniciar sesión..
        /// </summary>
        public static string SuccessPasswordReset {
            get {
                return ResourceManager.GetString("SuccessPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Autenticación.
        /// </summary>
        public static string TitleAuthenticationError {
            get {
                return ResourceManager.GetString("TitleAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string TitleConfirm {
            get {
                return ResourceManager.GetString("TitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación .
        /// </summary>
        public static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Conexión.
        /// </summary>
        public static string TitleConnectionError {
            get {
                return ResourceManager.GetString("TitleConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información..
        /// </summary>
        public static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        public static string TitlePay {
            get {
                return ResourceManager.GetString("TitlePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Completo.
        /// </summary>
        public static string TitleRegistrationComplete {
            get {
                return ResourceManager.GetString("TitleRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Registro.
        /// </summary>
        public static string TitleRegistrationError {
            get {
                return ResourceManager.GetString("TitleRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string TitleResetPassword {
            get {
                return ResourceManager.GetString("TitleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña restablecida.
        /// </summary>
        public static string TitleResetPasswordSuccess {
            get {
                return ResourceManager.GetString("TitleResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito .
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string TitleValidation {
            get {
                return ResourceManager.GetString("TitleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña .
        /// </summary>
        public static string UserProfileChangePassword {
            get {
                return ResourceManager.GetString("UserProfileChangePassword", resourceCulture);
            }
        }
    }
}
