//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánCliente.ServicePresence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePresence.IPresence", CallbackContract=typeof(ConquiánCliente.ServicePresence.IPresenceCallback))]
    public interface IPresence {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Subscribe")]
        void Subscribe(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Unsubscribe")]
        void Unsubscribe(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Ping")]
        void Ping(int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Ping")]
        System.Threading.Tasks.Task PingAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPresenceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/OnFriendStatusChanged")]
        void OnFriendStatusChanged(int friendId, int newStatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPresenceChannel : ConquiánCliente.ServicePresence.IPresence, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresenceClient : System.ServiceModel.DuplexClientBase<ConquiánCliente.ServicePresence.IPresence>, ConquiánCliente.ServicePresence.IPresence {
        
        public PresenceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PresenceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PresenceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PresenceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PresenceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(int idPlayer) {
            base.Channel.Subscribe(idPlayer);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(int idPlayer) {
            return base.Channel.SubscribeAsync(idPlayer);
        }
        
        public void Unsubscribe(int idPlayer) {
            base.Channel.Unsubscribe(idPlayer);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer) {
            return base.Channel.UnsubscribeAsync(idPlayer);
        }
        
        public void Ping(int userId) {
            base.Channel.Ping(userId);
        }
        
        public System.Threading.Tasks.Task PingAsync(int userId) {
            return base.Channel.PingAsync(userId);
        }
    }
}
